### ISSUE TITLE
commands get lost

### ISSUE THREAD

**Issue by smadep** [nicollasricas/streamdeckvs#1]
after configuration and successful working suddenly for some of the "buttons" the command-field is empty

**Comment by smadep** [comment]
the problem seems to be partly related to not leaving the command input focusing on other input before selecting different button. when going back to previous button the command-input is empty
StreamDeck v. 4.4.1

**Comment by nicollasricas** [comment]
Thank you for reporting and also investigate it further. I will have this fixed tonight.
