### ISSUE TITLE
Send VS Commands when child application has focus

### ISSUE THREAD

**Issue by mcattle** [nicollasricas/streamdeckvs#2]
First of all, thank you for this Stream Deck extension.

I've just started using my Stream Deck Mini with Visual Studio 2017 for application debugging, namely Debug / Break / Stop / Step Into / Step Over / Step Out.  I have these properly mapped to their VS commands, however the Visual Studio IDE needs to have focus in order to issue these commands.

I don't know if it's possible, but when VS is debugging an application (which it runs as a child process) and that application has focus, is it possible for these commands to be sent to the parent VS IDE process?  This would be particularly useful for the Break and Stop commands.

**Comment by nicollasricas** [comment]
I think this could be done. I will take a look at that.

Thank you for suggesting.

**Comment by nicollasricas** [comment]
Which kind of project are you working on? I'm asking because I've managed to get it working, but not all kind.

I've tested with a few projects that I have on my machine and it's working:

- UWP (.NET)
- WPF (.NET)
- WPF (.NET, required administrative privileges), requires Stream Deck software to be running with administrative privileges or it won't work (can be handled later).
- Console (.NET)

Projects that didn't work:

- Console (.NET Core) for some reason the console window which will be focused is not attached to the debugger itself, there's a middleware between, so I couldn't figure out a way to track it. **I will give another try**.

Tomorrow I will give a try with web applications/api and see how it goes.

**Comment by mcattle** [comment]
I primarily develop console (.NET) and Windows Forms (.NET) applications.  I also develop .NET Core services / console applications, but generally use VS Code for those.

**Comment by nicollasricas** [comment]
Could you give it a try and let me know if it's working? It works with everything I tried except for web projects or projects that have a middleware between the debug as mentioned before.
[com.nicollasr.streamdeckvs.streamDeckPlugin.zip](https://github.com/nicollasricas/streamdeckvs/files/3970323/com.nicollasr.streamdeckvs.streamDeckPlugin.zip)

**Comment by mcattle** [comment]
Sorry, I've been away from the office the past few weeks, I'll give the changes a try this week.

I'm also building a [StreamDeck button image library for Visual Studio commands](https://github.com/mcattle/StreamDeck-VisualStudio-ButtonGraphics), based off the Visual Studio 2017 Image Library (as they have not yet released a VS2019 version), and you're welcome to use those images in your plugin if you'd like to extend it further.

**Comment by nicollasricas** [comment]
Hey,

Try with the latest version that I release or wait until Elgato updates on the store.

Thank you for your idea it proved very useful.

I could use a generic "execute command" icon... Is there any? I've been using your icon library since I starred, but for my keys.

**Comment by mcattle** [comment]
I'll wait until Elgato updates the store, to keep installation simple.

The previous icon library was a quick hack to get basic icons to use, but it has been replaced last night with a new library based off the Visual Studio 2017 Image Library by rendering the source .svg files to .png.  I've just added a **visualstudio-commands/General** folder with some candidates for a generic execute command icon (or you could unzip the file in the **raw-graphics** folder to search for other candidates).  Unfortunately, the source library doesn't include Visual Studio logos, likely for trademark / copyright reasons.

**Comment by mcattle** [comment]
Just got the update, did a quick test, and it works beautifully with the child application in the foreground!
