### ISSUE TITLE
VS 2022 Support

### ISSUE THREAD

**Issue by rfnovoa** [nicollasricas/streamdeckvs#5]
Trying to integrate this into VS 2022 but I am not able to install Command Explorer on it. Any advice or plan to fix this as the plugin is unusable. VS 2019 works fine.

**Comment by nicollasricas** [comment]
Hey,

You can use the VS2019 commands ids in VSS2022 without any problems. Most of the commands have the same id, except for the new ones.

I hope Mads update his extension to Visual Studio 2022 soon to help us gather the command id for new features (for those who needed, which is not my case)

Best,
Nicollas R.

**Comment by rfnovoa** [comment]
Will try that, really appreciate your response!
