### ISSUE TITLE
"Old" commands nog longer work since plugin update to 3.3.2

### ISSUE THREAD

**Issue by LagoDannySuntjens** [nicollasricas/streamdeckvs#7]
Since the plugin is updated to version 3.3.2 my "old" VS commands are no longer working.
New created commands are executed correctly.

In the log I see many times the following errors:
`2022-02-02 13:53:06.5902|INFO|com.nicollasr.streamdeckvs|66|ROT Object Found !VisualStudio.DTE.16.0:98628`
`2022-02-02 13:53:06.5902|ERROR|com.nicollasr.streamdeckvs|66|Object reference not set to an instance of an object.`

I am using Microsoft Visual Studio Community 2019, Version 16.11.7

A workaround is updating (enter again the command in the field), but can take a lot of time if you have more than a few commands setup. Maybe there is an easier way?

**Comment by EngstromJimmy** [comment]
Oh, noes!
I feel responsible for this, I never tested the upgrade scenario.
I currently don't have access to my stream deck but I'll take a look this Friday and see if I can solve it some how.

**Comment by nicollasricas** [comment]
I'm responsible too. I'm busy right now, so I couldn't test it and push an update. I hope I have some time later to add a workflow to automate new releases and testing.

[github.com/nicollasricas/streamdeckvs/releases/latest](https://github.com/nicollasricas/streamdeckvs/releases/latest)
