### ISSUE TITLE
Command Explorer cannot be installed on vs22

### ISSUE THREAD

**Issue by BloodyMikey** [nicollasricas/streamdeckvs#8]
Command Explorer cannot be installed on vs22
![image](https://user-images.githubusercontent.com/7265198/154081899-c6b1f265-50d7-4deb-aa60-38f4ea27a829.png)

**Comment by EngstromJimmy** [comment]
Command explorer is written by Mads Kristensen, I'll ping him on Twitter to see if there is any updates coming =)

https://twitter.com/EngstromJimmy/status/1493628139171368963

**Comment by EngstromJimmy** [comment]
Apparently it is in the works in one way or another according to Mads.
You can use the keyboard shortcuts view in the Visual Studio options to find the command to use as well.

![image](https://user-images.githubusercontent.com/2390244/154123633-c4c417a6-a068-41ea-9ffc-065f27e4a5bb.png)

**Comment by nicollasricas** [comment]
> Apparently it is in the works in one way or another according to Mads. You can use the keyboard shortcuts view in the Visual Studio options to find the command to use as well.
> 
> ![image](https://user-images.githubusercontent.com/2390244/154123633-c4c417a6-a068-41ea-9ffc-065f27e4a5bb.png)

@EngstromJimmy I didn't know that you could find the commands ids on the keyboard options. Thanks for sharing and taking the time to look at this.

@BloodyMikey I will close the issue now. You can find the commands ids using the keyboard options or get them from Visual Studio 2019 and use it in Visual Studio 2022.
