### ISSUE TITLE
Enhancement Request: Add VS 2022 for this plugin

### ISSUE THREAD

**Issue by adamrosellc** [nicollasricas/streamdeckvs#9]
I have recently migrated to VS 2022 and would love you have this plugin there.

**Comment by EngstromJimmy** [comment]
It is available for VS2022 already :)
You probably have to install it again for VS2022 to pick it up :)

**Comment by adamrosellc** [comment]
Ah, I put this on the wrong github.  This was for the command explorer which I now see other requests for the same thing
